generators:
  'money-generator':
    item:
      name: "&2» &lMONEY GENERATOR"
      lore:
        - "&fPiazza questo generatore all'interno del tuo lotto per farmare soldi.    "
        - ""
        - "&a&l» LIVELLO %generator_level%"
      headID: "27938"
    info:
      value:
        type: TOKEN
        amount: 1
      levels:
        '1':
          money-price: 10000.0
          speed: 60
        '2':
          money-price: 20000.0
          speed: 30